name: komikuy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  html: ^0.15.4
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
